# Generated by Django 4.0.4 on 2022-06-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans', models.CharField(max_length=40)),
                ('val', models.IntegerField()),
                ('dtime', models.DateField()),
            ],
        ),
    ]
