# Generated by Django 4.0.4 on 2022-06-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_transac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transac',
            name='dtime',
            field=models.DateField(null=True),
        ),
    ]
