# Generated by Django 4.0.4 on 2022-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_transac_dtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('value', models.IntegerField()),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
